### ISSUE TITLE
Spamming error on latest (0.11.4) tML

### ISSUE THREAD

**Issue by nhilerion** [Ilyaki/TerrariaSplitScreen#10]
I really wanted to try out this mod but sadly its broken a bit.

[1/ERROR] [Terraria]: System.ArgumentOutOfRangeException: Field isActive was not found in Type Terraria.Main
Parameter name: propName
   at SplitScreen.AccessExtensions.SetPrivateFieldValue[T](Object obj, String propName, T val)
   at SplitScreen.Main_Update_Patcher.Prefix(GameTime gameTime)
   at DoUpdate_Patch1(Object gameTime, GameTime )
   at Terraria.Main.Update(GameTime gameTime)

I get this error every second after i try to host&play.

**Comment by AppleNick26** [comment]
Same here! The error repeats itself every second in the console while trying to host and play. The mod works on 32 bit versions of TML but not in the 64 bit version.
